####
# This Dockerfile is used in deliveryOrder to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/center .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/center
#
###
FROM 222.71.182.250:5000/os/oraclelinux:8-slim

ENV LANG=en_US.UTF-8
ENV TZ=Asia/Shanghai

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

USER 1001

CMD ["./application", "-Dspring.aot.enabled=true"]
